apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sns9vkdc1-nodejs 
  janus-idp.io/tekton: sns9vkdc1-nodejs
  backstage.io/kubernetes-id: sns9vkdc1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sns9vkdc1-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml